// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.0--dev
// source: call_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallSmartContractHashData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress []byte `protobuf:"bytes,1,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CallSmartContractHashData) Reset() {
	*x = CallSmartContractHashData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_call_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallSmartContractHashData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSmartContractHashData) ProtoMessage() {}

func (x *CallSmartContractHashData) ProtoReflect() protoreflect.Message {
	mi := &file_call_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSmartContractHashData.ProtoReflect.Descriptor instead.
func (*CallSmartContractHashData) Descriptor() ([]byte, []int) {
	return file_call_data_proto_rawDescGZIP(), []int{0}
}

func (x *CallSmartContractHashData) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *CallSmartContractHashData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CallSmartContractData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress []byte `protobuf:"bytes,1,opt,name=ToAddress,proto3" json:"ToAddress,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Sign      []byte `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *CallSmartContractData) Reset() {
	*x = CallSmartContractData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_call_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallSmartContractData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSmartContractData) ProtoMessage() {}

func (x *CallSmartContractData) ProtoReflect() protoreflect.Message {
	mi := &file_call_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSmartContractData.ProtoReflect.Descriptor instead.
func (*CallSmartContractData) Descriptor() ([]byte, []int) {
	return file_call_data_proto_rawDescGZIP(), []int{1}
}

func (x *CallSmartContractData) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *CallSmartContractData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallSmartContractData) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type CallSmartContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CallSmartContractResponse) Reset() {
	*x = CallSmartContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_call_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallSmartContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSmartContractResponse) ProtoMessage() {}

func (x *CallSmartContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_call_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSmartContractResponse.ProtoReflect.Descriptor instead.
func (*CallSmartContractResponse) Descriptor() ([]byte, []int) {
	return file_call_data_proto_rawDescGZIP(), []int{2}
}

func (x *CallSmartContractResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CallSmartContractResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_call_data_proto protoreflect.FileDescriptor

var file_call_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x19,
	0x43, 0x61, 0x6c, 0x6c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x54, 0x6f,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x15, 0x43,
	0x61, 0x6c, 0x6c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x22, 0x43, 0x0a, 0x19, 0x43, 0x61,
	0x6c, 0x6c, 0x53, 0x6d, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_call_data_proto_rawDescOnce sync.Once
	file_call_data_proto_rawDescData = file_call_data_proto_rawDesc
)

func file_call_data_proto_rawDescGZIP() []byte {
	file_call_data_proto_rawDescOnce.Do(func() {
		file_call_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_call_data_proto_rawDescData)
	})
	return file_call_data_proto_rawDescData
}

var file_call_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_call_data_proto_goTypes = []interface{}{
	(*CallSmartContractHashData)(nil), // 0: call_data.CallSmartContractHashData
	(*CallSmartContractData)(nil),     // 1: call_data.CallSmartContractData
	(*CallSmartContractResponse)(nil), // 2: call_data.CallSmartContractResponse
}
var file_call_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_call_data_proto_init() }
func file_call_data_proto_init() {
	if File_call_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_call_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallSmartContractHashData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_call_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallSmartContractData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_call_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallSmartContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_call_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_call_data_proto_goTypes,
		DependencyIndexes: file_call_data_proto_depIdxs,
		MessageInfos:      file_call_data_proto_msgTypes,
	}.Build()
	File_call_data_proto = out.File
	file_call_data_proto_rawDesc = nil
	file_call_data_proto_goTypes = nil
	file_call_data_proto_depIdxs = nil
}
