// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.0--dev
// source: chain_event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"` // Block height
	Logs  []*Log `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`   // Hash of the parent block
}

func (x *ChainEvent) Reset() {
	*x = ChainEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chain_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainEvent) ProtoMessage() {}

func (x *ChainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chain_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainEvent.ProtoReflect.Descriptor instead.
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return file_chain_event_proto_rawDescGZIP(), []int{0}
}

func (x *ChainEvent) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ChainEvent) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_chain_event_proto protoreflect.FileDescriptor

var file_chain_event_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x1a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6c,
	0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x6f,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4c,
	0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chain_event_proto_rawDescOnce sync.Once
	file_chain_event_proto_rawDescData = file_chain_event_proto_rawDesc
)

func file_chain_event_proto_rawDescGZIP() []byte {
	file_chain_event_proto_rawDescOnce.Do(func() {
		file_chain_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_chain_event_proto_rawDescData)
	})
	return file_chain_event_proto_rawDescData
}

var file_chain_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chain_event_proto_goTypes = []interface{}{
	(*ChainEvent)(nil), // 0: chain_event.ChainEvent
	(*Block)(nil),      // 1: block.Block
	(*Log)(nil),        // 2: log.Log
}
var file_chain_event_proto_depIdxs = []int32{
	1, // 0: chain_event.ChainEvent.block:type_name -> block.Block
	2, // 1: chain_event.ChainEvent.logs:type_name -> log.Log
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chain_event_proto_init() }
func file_chain_event_proto_init() {
	if File_chain_event_proto != nil {
		return
	}
	file_block_proto_init()
	file_log_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chain_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chain_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_event_proto_goTypes,
		DependencyIndexes: file_chain_event_proto_depIdxs,
		MessageInfos:      file_chain_event_proto_msgTypes,
	}.Build()
	File_chain_event_proto = out.File
	file_chain_event_proto_rawDesc = nil
	file_chain_event_proto_goTypes = nil
	file_chain_event_proto_depIdxs = nil
}
