// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file account.proto (package account, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file account.proto.
 */
export const file_account: GenFile = /*@__PURE__*/
  fileDesc("Cg1hY2NvdW50LnByb3RvEgdhY2NvdW50IlIKB0FjY291bnQSDQoFbm9uY2UYASABKAQSDwoHYmFsYW5jZRgCIAEoCRIUCgxzdG9yYWdlX3Jvb3QYAyABKAwSEQoJY29kZV9oYXNoGAQgASgMQghaBi9wcm90b2IGcHJvdG8z");

/**
 * Account represents an Ethereum-like account
 *
 * @generated from message account.Account
 */
export type Account = Message<"account.Account"> & {
  /**
   * Number of transactions sent
   *
   * @generated from field: uint64 nonce = 1;
   */
  nonce: bigint;

  /**
   * Account balance in wei (as string to preserve big.Int)
   *
   * @generated from field: string balance = 2;
   */
  balance: string;

  /**
   * Root hash of the account storage trie
   *
   * @generated from field: bytes storage_root = 3;
   */
  storageRoot: Uint8Array;

  /**
   * Hash of the EVM code
   *
   * @generated from field: bytes code_hash = 4;
   */
  codeHash: Uint8Array;
};

/**
 * Describes the message account.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/
  messageDesc(file_account, 0);

