// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file chain_event.proto (package chain_event, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Block } from "./block_pb";
import { file_block } from "./block_pb";
import type { Log } from "./log_pb";
import { file_log } from "./log_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chain_event.proto.
 */
export const file_chain_event: GenFile = /*@__PURE__*/
  fileDesc("ChFjaGFpbl9ldmVudC5wcm90bxILY2hhaW5fZXZlbnQiQQoKQ2hhaW5FdmVudBIbCgVibG9jaxgBIAEoCzIMLmJsb2NrLkJsb2NrEhYKBGxvZ3MYAiADKAsyCC5sb2cuTG9nQghaBi9wcm90b2IGcHJvdG8z", [file_block, file_log]);

/**
 * @generated from message chain_event.ChainEvent
 */
export type ChainEvent = Message<"chain_event.ChainEvent"> & {
  /**
   * Block height
   *
   * @generated from field: block.Block block = 1;
   */
  block?: Block;

  /**
   * Hash of the parent block
   *
   * @generated from field: repeated log.Log logs = 2;
   */
  logs: Log[];
};

/**
 * Describes the message chain_event.ChainEvent.
 * Use `create(ChainEventSchema)` to create a new message.
 */
export const ChainEventSchema: GenMessage<ChainEvent> = /*@__PURE__*/
  messageDesc(file_chain_event, 0);

