// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file log.proto (package log, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file log.proto.
 */
export const file_log: GenFile = /*@__PURE__*/
  fileDesc("Cglsb2cucHJvdG8SA2xvZyKlAQoDTG9nEg8KB2FkZHJlc3MYASABKAwSDgoGdG9waWNzGAIgAygMEgwKBGRhdGEYAyABKAwSEQoJbG9nX2luZGV4GAQgASgNEhQKDGJsb2NrX251bWJlchgFIAEoBBIPCgd0eF9oYXNoGAYgASgMEhAKCHR4X2luZGV4GAcgASgNEhIKCmJsb2NrX2hhc2gYCCABKAwSDwoHcmVtb3ZlZBgJIAEoCCI4CgdMb2dEYXRhEg8KB2FkZHJlc3MYASABKAwSDgoGdG9waWNzGAIgAygMEgwKBGRhdGEYAyABKAxCCFoGL3Byb3RvYgZwcm90bzM");

/**
 * @generated from message log.Log
 */
export type Log = Message<"log.Log"> & {
  /**
   * 20 bytes
   *
   * @generated from field: bytes address = 1;
   */
  address: Uint8Array;

  /**
   * 32 bytes each
   *
   * @generated from field: repeated bytes topics = 2;
   */
  topics: Uint8Array[];

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  /**
   * @generated from field: uint32 log_index = 4;
   */
  logIndex: number;

  /**
   * @generated from field: uint64 block_number = 5;
   */
  blockNumber: bigint;

  /**
   * @generated from field: bytes tx_hash = 6;
   */
  txHash: Uint8Array;

  /**
   * @generated from field: uint32 tx_index = 7;
   */
  txIndex: number;

  /**
   * @generated from field: bytes block_hash = 8;
   */
  blockHash: Uint8Array;

  /**
   * For chain reorgs
   *
   * @generated from field: bool removed = 9;
   */
  removed: boolean;
};

/**
 * Describes the message log.Log.
 * Use `create(LogSchema)` to create a new message.
 */
export const LogSchema: GenMessage<Log> = /*@__PURE__*/
  messageDesc(file_log, 0);

/**
 * @generated from message log.LogData
 */
export type LogData = Message<"log.LogData"> & {
  /**
   * 20 bytes
   *
   * @generated from field: bytes address = 1;
   */
  address: Uint8Array;

  /**
   * 32 bytes each
   *
   * @generated from field: repeated bytes topics = 2;
   */
  topics: Uint8Array[];

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;
};

/**
 * Describes the message log.LogData.
 * Use `create(LogDataSchema)` to create a new message.
 */
export const LogDataSchema: GenMessage<LogData> = /*@__PURE__*/
  messageDesc(file_log, 1);

