// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file mpt.proto (package mpt, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mpt.proto.
 */
export const file_mpt: GenFile = /*@__PURE__*/
  fileDesc("CgltcHQucHJvdG8SA21wdCI4CgdNUFROb2RlEh8KBHR5cGUYASABKA4yES5tcHQuTVBUTk9ERV9UWVBFEgwKBGRhdGEYAiABKAwiKwoLTVBURnVsbE5vZGUSDQoFbm9kZXMYASADKAwSDQoFdmFsdWUYAiABKAwiKgoMTVBUU2hvcnROb2RlEgsKA2tleRgBIAEoDBINCgV2YWx1ZRgCIAEoDCouCgxNUFROT0RFX1RZUEUSCAoERlVMTBAAEgkKBVNIT1JUEAESCQoFVkFMVUUQAkIIWgYvcHJvdG9iBnByb3RvMw");

/**
 * @generated from message mpt.MPTNode
 */
export type MPTNode = Message<"mpt.MPTNode"> & {
  /**
   * @generated from field: mpt.MPTNODE_TYPE type = 1;
   */
  type: MPTNODE_TYPE;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message mpt.MPTNode.
 * Use `create(MPTNodeSchema)` to create a new message.
 */
export const MPTNodeSchema: GenMessage<MPTNode> = /*@__PURE__*/
  messageDesc(file_mpt, 0);

/**
 * @generated from message mpt.MPTFullNode
 */
export type MPTFullNode = Message<"mpt.MPTFullNode"> & {
  /**
   * 16 element of 32 bytes hash
   *
   * @generated from field: repeated bytes nodes = 1;
   */
  nodes: Uint8Array[];

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message mpt.MPTFullNode.
 * Use `create(MPTFullNodeSchema)` to create a new message.
 */
export const MPTFullNodeSchema: GenMessage<MPTFullNode> = /*@__PURE__*/
  messageDesc(file_mpt, 1);

/**
 * @generated from message mpt.MPTShortNode
 */
export type MPTShortNode = Message<"mpt.MPTShortNode"> & {
  /**
   * @generated from field: bytes key = 1;
   */
  key: Uint8Array;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message mpt.MPTShortNode.
 * Use `create(MPTShortNodeSchema)` to create a new message.
 */
export const MPTShortNodeSchema: GenMessage<MPTShortNode> = /*@__PURE__*/
  messageDesc(file_mpt, 2);

/**
 * @generated from enum mpt.MPTNODE_TYPE
 */
export enum MPTNODE_TYPE {
  /**
   * @generated from enum value: FULL = 0;
   */
  FULL = 0,

  /**
   * @generated from enum value: SHORT = 1;
   */
  SHORT = 1,

  /**
   * @generated from enum value: VALUE = 2;
   */
  VALUE = 2,
}

/**
 * Describes the enum mpt.MPTNODE_TYPE.
 */
export const MPTNODE_TYPESchema: GenEnum<MPTNODE_TYPE> = /*@__PURE__*/
  enumDesc(file_mpt, 0);

