// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file receipt.proto (package receipt, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Log, LogData } from "./log_pb";
import { file_log } from "./log_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file receipt.proto.
 */
export const file_receipt: GenFile = /*@__PURE__*/
  fileDesc("Cg1yZWNlaXB0LnByb3RvEgdyZWNlaXB0IpkCCgdSZWNlaXB0Eg8KB3R4X2hhc2gYASABKAwSEgoKYmxvY2tfaGFzaBgCIAEoDBIUCgxibG9ja19udW1iZXIYAyABKAQSEAoIdHhfaW5kZXgYBCABKA0SDAoEZnJvbRgFIAEoDBIKCgJ0bxgGIAEoDBIOCgZhbW91bnQYByABKAwSGwoTY3VtdWxhdGl2ZV9nYXNfdXNlZBgIIAEoBBIQCghnYXNfdXNlZBgJIAEoBBIYChBjb250cmFjdF9hZGRyZXNzGAogASgMEhYKBGxvZ3MYCyADKAsyCC5sb2cuTG9nEhIKCnBvc3Rfc3RhdGUYDCABKAwSEgoKbG9nc19ibG9vbRgNIAEoDBIOCgZzdGF0dXMYDiABKA0ifgoLUmVjZWlwdERhdGESEgoKcG9zdF9zdGF0ZRgBIAEoDBIOCgZzdGF0dXMYAiABKA0SGwoTY3VtdWxhdGl2ZV9nYXNfdXNlZBgDIAEoBBISCgpsb2dzX2Jsb29tGAQgASgMEhoKBGxvZ3MYBSADKAsyDC5sb2cuTG9nRGF0YSIuCghSZWNlaXB0cxIiCghyZWNlaXB0cxgBIAMoCzIQLnJlY2VpcHQuUmVjZWlwdEIIWgYvcHJvdG9iBnByb3RvMw", [file_log]);

/**
 * @generated from message receipt.Receipt
 */
export type Receipt = Message<"receipt.Receipt"> & {
  /**
   * @generated from field: bytes tx_hash = 1;
   */
  txHash: Uint8Array;

  /**
   * @generated from field: bytes block_hash = 2;
   */
  blockHash: Uint8Array;

  /**
   * @generated from field: uint64 block_number = 3;
   */
  blockNumber: bigint;

  /**
   * @generated from field: uint32 tx_index = 4;
   */
  txIndex: number;

  /**
   * 20 bytes
   *
   * @generated from field: bytes from = 5;
   */
  from: Uint8Array;

  /**
   * 20 bytes, empty if contract creation
   *
   * @generated from field: bytes to = 6;
   */
  to: Uint8Array;

  /**
   * @generated from field: bytes amount = 7;
   */
  amount: Uint8Array;

  /**
   * @generated from field: uint64 cumulative_gas_used = 8;
   */
  cumulativeGasUsed: bigint;

  /**
   * @generated from field: uint64 gas_used = 9;
   */
  gasUsed: bigint;

  /**
   * 20 bytes, empty if not contract creation
   *
   * @generated from field: bytes contract_address = 10;
   */
  contractAddress: Uint8Array;

  /**
   * @generated from field: repeated log.Log logs = 11;
   */
  logs: Log[];

  /**
   * @generated from field: bytes post_state = 12;
   */
  postState: Uint8Array;

  /**
   * @generated from field: bytes logs_bloom = 13;
   */
  logsBloom: Uint8Array;

  /**
   * @generated from field: uint32 status = 14;
   */
  status: number;
};

/**
 * Describes the message receipt.Receipt.
 * Use `create(ReceiptSchema)` to create a new message.
 */
export const ReceiptSchema: GenMessage<Receipt> = /*@__PURE__*/
  messageDesc(file_receipt, 0);

/**
 * @generated from message receipt.ReceiptData
 */
export type ReceiptData = Message<"receipt.ReceiptData"> & {
  /**
   * @generated from field: bytes post_state = 1;
   */
  postState: Uint8Array;

  /**
   * 1 = success, 0 = failure
   *
   * @generated from field: uint32 status = 2;
   */
  status: number;

  /**
   * @generated from field: uint64 cumulative_gas_used = 3;
   */
  cumulativeGasUsed: bigint;

  /**
   * 256 bytes
   *
   * @generated from field: bytes logs_bloom = 4;
   */
  logsBloom: Uint8Array;

  /**
   * @generated from field: repeated log.LogData logs = 5;
   */
  logs: LogData[];
};

/**
 * Describes the message receipt.ReceiptData.
 * Use `create(ReceiptDataSchema)` to create a new message.
 */
export const ReceiptDataSchema: GenMessage<ReceiptData> = /*@__PURE__*/
  messageDesc(file_receipt, 1);

/**
 * @generated from message receipt.Receipts
 */
export type Receipts = Message<"receipt.Receipts"> & {
  /**
   * @generated from field: repeated receipt.Receipt receipts = 1;
   */
  receipts: Receipt[];
};

/**
 * Describes the message receipt.Receipts.
 * Use `create(ReceiptsSchema)` to create a new message.
 */
export const ReceiptsSchema: GenMessage<Receipts> = /*@__PURE__*/
  messageDesc(file_receipt, 2);

