// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file transaction.proto (package transaction, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file transaction.proto.
 */
export const file_transaction: GenFile = /*@__PURE__*/
  fileDesc("ChF0cmFuc2FjdGlvbi5wcm90bxILdHJhbnNhY3Rpb24imQEKC1RyYW5zYWN0aW9uEhEKCVRvQWRkcmVzcxgBIAEoDBINCgVOb25jZRgCIAEoBBIOCgZBbW91bnQYAyABKAwSDAoERGF0YRgEIAEoDBILCgNHYXMYBSABKAQSEAoIR2FzUHJpY2UYBiABKAwSDwoHTWVzc2FnZRgHIAEoCRIMCgRTaWduGAggASgMEgwKBEhhc2gYCSABKAwilgEKE1RyYW5zYWN0aW9uU2lnbkRhdGESEQoJVG9BZGRyZXNzGAEgASgMEg0KBU5vbmNlGAIgASgEEg4KBkFtb3VudBgDIAEoDBIMCgREYXRhGAQgASgMEgsKA0dhcxgFIAEoBBIQCghHYXNQcmljZRgGIAEoDBIPCgdNZXNzYWdlGAcgASgJEg8KB0NoYWluSWQYCCABKAwikwEKE1RyYW5zYWN0aW9uSGFzaERhdGESEQoJVG9BZGRyZXNzGAEgASgMEg0KBU5vbmNlGAIgASgEEg4KBkFtb3VudBgDIAEoDBIMCgREYXRhGAQgASgMEgsKA0dhcxgFIAEoBBIQCghHYXNQcmljZRgGIAEoDBIPCgdNZXNzYWdlGAcgASgJEgwKBFNpZ24YCCABKAwiTwoWVHJhbnNhY3Rpb25Mb29rdXBFbnRyeRIRCglCbG9ja0hhc2gYASABKAwSEwoLQmxvY2tOdW1iZXIYAiABKAQSDQoFSW5kZXgYAyABKARCCFoGL3Byb3RvYgZwcm90bzM");

/**
 * @generated from message transaction.Transaction
 */
export type Transaction = Message<"transaction.Transaction"> & {
  /**
   * @generated from field: bytes ToAddress = 1;
   */
  ToAddress: Uint8Array;

  /**
   * @generated from field: uint64 Nonce = 2;
   */
  Nonce: bigint;

  /**
   * @generated from field: bytes Amount = 3;
   */
  Amount: Uint8Array;

  /**
   * @generated from field: bytes Data = 4;
   */
  Data: Uint8Array;

  /**
   * @generated from field: uint64 Gas = 5;
   */
  Gas: bigint;

  /**
   * @generated from field: bytes GasPrice = 6;
   */
  GasPrice: Uint8Array;

  /**
   * @generated from field: string Message = 7;
   */
  Message: string;

  /**
   * @generated from field: bytes Sign = 8;
   */
  Sign: Uint8Array;

  /**
   * @generated from field: bytes Hash = 9;
   */
  Hash: Uint8Array;
};

/**
 * Describes the message transaction.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export const TransactionSchema: GenMessage<Transaction> = /*@__PURE__*/
  messageDesc(file_transaction, 0);

/**
 * @generated from message transaction.TransactionSignData
 */
export type TransactionSignData = Message<"transaction.TransactionSignData"> & {
  /**
   * @generated from field: bytes ToAddress = 1;
   */
  ToAddress: Uint8Array;

  /**
   * @generated from field: uint64 Nonce = 2;
   */
  Nonce: bigint;

  /**
   * @generated from field: bytes Amount = 3;
   */
  Amount: Uint8Array;

  /**
   * @generated from field: bytes Data = 4;
   */
  Data: Uint8Array;

  /**
   * @generated from field: uint64 Gas = 5;
   */
  Gas: bigint;

  /**
   * @generated from field: bytes GasPrice = 6;
   */
  GasPrice: Uint8Array;

  /**
   * @generated from field: string Message = 7;
   */
  Message: string;

  /**
   * @generated from field: bytes ChainId = 8;
   */
  ChainId: Uint8Array;
};

/**
 * Describes the message transaction.TransactionSignData.
 * Use `create(TransactionSignDataSchema)` to create a new message.
 */
export const TransactionSignDataSchema: GenMessage<TransactionSignData> = /*@__PURE__*/
  messageDesc(file_transaction, 1);

/**
 * @generated from message transaction.TransactionHashData
 */
export type TransactionHashData = Message<"transaction.TransactionHashData"> & {
  /**
   * @generated from field: bytes ToAddress = 1;
   */
  ToAddress: Uint8Array;

  /**
   * @generated from field: uint64 Nonce = 2;
   */
  Nonce: bigint;

  /**
   * @generated from field: bytes Amount = 3;
   */
  Amount: Uint8Array;

  /**
   * @generated from field: bytes Data = 4;
   */
  Data: Uint8Array;

  /**
   * @generated from field: uint64 Gas = 5;
   */
  Gas: bigint;

  /**
   * @generated from field: bytes GasPrice = 6;
   */
  GasPrice: Uint8Array;

  /**
   * @generated from field: string Message = 7;
   */
  Message: string;

  /**
   * @generated from field: bytes Sign = 8;
   */
  Sign: Uint8Array;
};

/**
 * Describes the message transaction.TransactionHashData.
 * Use `create(TransactionHashDataSchema)` to create a new message.
 */
export const TransactionHashDataSchema: GenMessage<TransactionHashData> = /*@__PURE__*/
  messageDesc(file_transaction, 2);

/**
 * @generated from message transaction.TransactionLookupEntry
 */
export type TransactionLookupEntry = Message<"transaction.TransactionLookupEntry"> & {
  /**
   * @generated from field: bytes BlockHash = 1;
   */
  BlockHash: Uint8Array;

  /**
   * @generated from field: uint64 BlockNumber = 2;
   */
  BlockNumber: bigint;

  /**
   * @generated from field: uint64 Index = 3;
   */
  Index: bigint;
};

/**
 * Describes the message transaction.TransactionLookupEntry.
 * Use `create(TransactionLookupEntrySchema)` to create a new message.
 */
export const TransactionLookupEntrySchema: GenMessage<TransactionLookupEntry> = /*@__PURE__*/
  messageDesc(file_transaction, 3);

